# Generated by Django 2.0.3 on 2018-10-20 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('franquicias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes_Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idClientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Fecha_Consumo', models.CharField(max_length=50)),
                ('Observacion', models.CharField(max_length=50)),
                ('Precion_Consumo', models.CharField(max_length=50)),
                ('Fecha_Compra', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Productos_Franquicia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFranquicia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franquicias.Franquicias')),
                ('idProductos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Productos')),
            ],
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=50)),
                ('Fecha_Caducidad', models.CharField(max_length=50)),
                ('Ingredientes', models.CharField(max_length=50)),
                ('idProductos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Productos')),
            ],
        ),
        migrations.AddField(
            model_name='clientes_productos',
            name='idProductos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Productos'),
        ),
    ]
