# Generated by Django 2.1.2 on 2018-11-01 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('ingrediente1', models.CharField(max_length=50)),
                ('cant_ingrediente1', models.CharField(max_length=50)),
                ('ingrediente2', models.CharField(max_length=50)),
                ('cant_ingrediente2', models.CharField(max_length=50)),
                ('ingrediente3', models.CharField(max_length=50)),
                ('cant_ingrediente3', models.CharField(max_length=50)),
                ('preparacion', models.CharField(max_length=50)),
                ('idProductos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Productos')),
            ],
        ),
    ]
