# Generated by Django 2.1.2 on 2018-11-01 19:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20181101_1443'),
        ('producto', '0002_recetas'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas',
            name='idClientes',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='usuario.Clientes'),
            preserve_default=False,
        ),
    ]
