# Generated by Django 2.1.2 on 2018-11-01 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_recetas_idclientes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recetas',
            old_name='idClientes',
            new_name='idCliente',
        ),
    ]
