# Generated by Django 2.1.2 on 2018-11-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20181101_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recetas',
            old_name='idCliente',
            new_name='idClientes',
        ),
    ]
