# Generated by Django 2.1.2 on 2018-11-02 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20181101_1443'),
        ('producto', '0005_auto_20181101_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Factura', models.CharField(max_length=50)),
                ('idClientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Clientes')),
                ('idProductos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Productos')),
            ],
        ),
        migrations.RemoveField(
            model_name='clientes_productos',
            name='idClientes',
        ),
        migrations.RemoveField(
            model_name='clientes_productos',
            name='idProductos',
        ),
        migrations.DeleteModel(
            name='Clientes_Productos',
        ),
    ]
