# Generated by Django 2.1.2 on 2018-11-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Nombre',
            field=models.CharField(max_length=50),
        ),
    ]
